(load! +secrets)

(when (featurep 'evil)
  (load! +bindings)
  (load! +company)
  (load! +custom-functions)
  (load! +custom-text-objects)
  (load! +el)
  (load! +evil)
  (load! +git)
  (load! +haskell)
  (load! +idris)
  (load! +irc)
  (load! +js)
  ;; (load! +lsp)
  (load! +markdown)
  (load! +org)
  (load! +slack)
  (load! +spotify)
  (load! +style)
  (load! +ui))

